---
- hosts: IFB_VM
  remote_user: root

  tasks:
  - name: Check if port 80 is allowed
    shell: iptables -L | grep -q "Allow http" && echo -n yes || echo -n no
    register: check_allow_http
    changed_when: no
    always_run: yes

  - name: Allow port 80
    command: iptables -I INPUT 5 -i eth0 -p tcp --dport 80 -m comment --comment "Allow http" -m state --state NEW,ESTABLISHED -j ACCEPT
    when: check_allow_http.stdout == "no"
    notify:
      - Save iptables

  - name: Check if port 443 is allowed
    shell: iptables -L | grep -q "Allow https" && echo -n yes || echo -n no
    register: check_allow_https
    changed_when: no
    always_run: yes

  - name: Allow port 443
    command: iptables -I INPUT 5 -i eth0 -p tcp --dport 443 -m comment --comment "Allow http" -m state --state NEW,ESTABLISHED -j ACCEPT
    when: check_allow_https.stdout == "no"
    notify:
      - Save iptables

  - name: install Java Develoment Kit  (OpenJDK)
    yum: name=java-1.8.0-openjdk-devel.x86_64 state=present

  - name: install MongoDB
    yum: name=mongodb state=present

  - name: install MongoDB-Server
    yum: name=mongodb-server state=present

  - name: create ~/mydisk/data/db mongodb directory
    file: path=~/mydisk/data/db state=directory mode=0755

  - name: run MongoDB
    shell: mongod --dbpath ~/mydisk/data/db &

  - name : copy SyMeTRIC API server jar
    copy: src=/Users/gaignard-a/devSymApi/target/datahub-api-1.0-SNAPSHOT-datahub-launcher.jar dest=~/datahub-api-1.0-SNAPSHOT-datahub-launcher.jar owner=root group=root mode=644

  - name: start SyMeTRIC
    shell: java -jar ~/datahub-api-1.0-SNAPSHOT-datahub-launcher.jar -p 80
    async: 60
    poll: 5

  handlers:
    - name: Save iptables
      shell: iptables-save
